# Generated by Django 6.0.3 on 2026-03-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.CharField(max_length=100)),
                ('burst', models.CharField(max_length=100)),
                ('quantum', models.IntegerField()),
                ('fcfs_avg', models.FloatField()),
                ('sjf_avg', models.FloatField()),
                ('rr_avg', models.FloatField()),
                ('best_algo', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
